### ISSUE TITLE
Unclassified sequences TAXID

### ISSUE THREAD

**Issue by maxibor** [nick-youngblut/gtdb_to_taxdump#13]
In the NCBI taxonomy, there is on particulary useful TAXID: [12908](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=12908&lvl=3&lin=f&keep=1&srchmode=1&unlock) for *unclassified sequences*.

Would it be possible to preserve 12908 for unclassified sequences in `gtdb_to_taxump` or to add an extra (stable) TAXID for unclassified sequences ?

**Comment by nick-youngblut** [comment]
It might be best to just point potential users to https://github.com/shenwei356/gtdb-taxdump

**Comment by shenwei356** [comment]
It's the first time I know `12908`. GTDB may have no such "unclassified sequences".

**Comment by maxibor** [comment]
It's a nice to have TAXID entry to report sequences that couldn't be attributed to any reference :)
Thanks @nick-youngblut and @shenwei356 , I'll have a look at https://github.com/shenwei356/gtdb-taxdump when TaxonKit v0.11.0 is released
