### ISSUE TITLE
lineage2taxid error (module 'gtdb_to_taxdump' has no attribute 'Dmp')

### ISSUE THREAD

**Issue by emaxortiz** [nick-youngblut/gtdb_to_taxdump#14]
Hi Nick.
Thanks for developing this tool. I'm trying to get the taxid using the GTDB-tk lineage output for the MAGs I recovered.
No matter what I try in my command, I'm getting the same error:

$ lineage2taxid.py gtdbtk.ar122.summary.tsv /ncbi_taxdump/names.dmp /ncbi_taxdump/nodes.dmp 

Traceback (most recent call last):
  File "/home/eortiz/.local/bin/lineage2taxid.py", line 125, in <module>
    main(args)
  File "/home/eortiz/.local/bin/lineage2taxid.py", line 116, in main
    G = gtdb2td.Dmp.load_dmp(args.names_dmp, args.nodes_dmp)
AttributeError: module 'gtdb_to_taxdump' has no attribute 'Dmp'

Any guidance about how to solve this?
Thank you.
Max

**Comment by nick-youngblut** [comment]
How did you install gtdb_to_taxdump? It seems that something is messed up with your PYTHONPATH

**Comment by nick-youngblut** [comment]
I'm closing this issue due to a lack of activity

**Comment by ggavelis** [comment]
Hello Nick,

I have an issue with this as well (using gtdb_to_taxdump v0.1.9).

If I run lineage2taxid.py on the suggested test lineages (In a file called **input_test.txt**, contents here: https://pastebin.com/H5qGQJTk )

**lineage2taxid.py input_test.txt names.dmp nodes.dmp**

I get a "Could not find taxid for lineage" error

Here is the full output:
`2025-07-30 11:08:48,398 - Loading file: names.dmp
2025-07-30 11:08:52,346 - Loading file: nodes.dmp
2025-07-30 11:09:10,214 -   No. of nodes: 2677468
2025-07-30 11:09:10,783 -   No. of edges: 2677467
2025-07-30 11:09:10,783 - Parsing file: input_test.txt
classification	taxid	taxid_rank
2025-07-30 11:09:12,471 - Could not find a taxid for lineage: d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcus_E;s__Ruminococcus_E bromii_B
d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcus_E;s__Ruminococcus_E bromii_B	NA	NA
2025-07-30 11:09:14,162 - Could not find a taxid for lineage: d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola plebeius_A
d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola plebeius_A	NA	NA`

For reference, my **names.dmp** and **nodes.dmp** files are from NCBI's newest taxdump.tar.gz release here: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/
But I also had the issue when I ran it using names.dmp and nodes.dmp from an older NCBI release (24-07-01)

And I installed gtdb_to_taxdump using conda, like so:
conda create --prefix gtdb_to_taxdump bioconda::gtdb_to_taxdump

Thanks for this super useful program! It's GTDB to NCBI lineage conversion has been invaluable,

 Best,

~Greg

**Comment by nick-youngblut** [comment]
@ggavelis I've since moved on to a couple of new positions since developing gtdb_to_taxdump.  Please post on the https://github.com/leylabmpi/gtdb_to_taxdump fork, and someone still in the Ley Lab should be able to help you

**Comment by ggavelis** [comment]
Thanks for the fast response and congrats on your new positions!  ~Greg
