### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by gruningerrj** [nick-youngblut/gtdb_to_taxdump#6]
This looks like a very useful tool but I am struggling to figure out how to install it and how to use the scripts. I tried to clone the repo using git and that seemed to work but none of the scripts will run. 

I have a set of MAGs that have been taxonomically characterized with gtdb-tk and I want to take those classifications and convert them to ncbi taxid so I can use the MAGs as a custom Kraken database. This looks like it would do what I am looking for but I am not sure how to install and then run it. Could you provide guidance as to whether this tool will work for that?
Thanks

**Comment by nick-youngblut** [comment]
It's just a couple of python scripts that vary in which dependencies are needed. See the README for the list fo dependencies.
